tel = '5522998939404'
wppUrl = 'https://wa.me/message/J2M33Y3DWRTIH1'
instaUrl = 'https://instagram.com/vittepapelaria'

[admin_credentials]

gpasqualette = {name = "Guilherme", password = "Fl@mengo2401!"}
evidal = {name = "Esther", password = "Esther461124"}